x = input('Write something: ')
print(type(x))
print('Is numeric?', x.isnumeric())
print('Is alpha?', x.isalpha())
print('Is alfanum? ', x.isalnum())
print('Is just space?', x.isspace())
print('Is it in capital letters?', x.isupper())
print('Is it in lower case?', x.islower())
print('Is it capitalised?', x.istitle())
